import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import nextConfig from '@/next.config'
import { setLazyProp } from 'next/dist/server/api-utils'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>HOME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.works}>
          <h2>Works</h2>
          <div className={styles.grid}>
            <div className={styles.card}>
              <h3>
                ECサイトの移転
              </h3>
              <span className={`${styles.badge} ${styles.purple}`}>EC-CUBE</span>
              <span className={`${styles.badge} ${styles.purple}`}>PHP</span>
              <p>
                クラウドで展開していたECサイトを、オープンソースを使用してレンタルサーバーに構築
              </p>
            </div>

            <div className={styles.card}>
              <h3>
                海外動画サイトの改修
              </h3>
              <span className={`${styles.badge} ${styles.purple}`}>CakePHP</span>
              <span className={`${styles.badge} ${styles.purple}`}>PHP</span>
              <p>
                多言語化対応。
              </p>
            </div>

            <div className={styles.card}>
              <h3>
                基幹システム構築
              </h3>
              <span className={`${styles.badge} ${styles.purple}`}>ASP.NET</span>
              <span className={`${styles.badge} ${styles.purple}`}>C#</span>
              <p>
                ERPパッケージを使用した企業向けシステム構築。
              </p>
            </div>

            <div className={styles.card}>
              <h3>
                社内システム開発
              </h3>
              <span className={`${styles.badge} ${styles.purple}`}>ASP.NET</span>
              <span className={`${styles.badge} ${styles.purple}`}>VB</span>
              <p>
              </p>
            </div>
          </div>
        </div>

      </main>
    </>
  )
}
